#!/usr/bin/env sh
printenv | more | grep ^VILOVEUL_ > /viloveul/.env
npm install --prefix /viloveul >/dev/null 2>&1
npm cache clean --force    
npm run build --prefix=/viloveul >/dev/null 2>&1
exec nginx -g 'daemon off;'
